# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "CocoaPods"
  lande :cocoapods do
    cocoapods(
      use_bundle_exec: true,
      podfile: "./Podfile"
    )
  end

  desc "SwiftLint"
  lane :swiftlint do
    swiftlint(
      mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
      path: "./EshopHacker",       # Specify path to lint (optional)
      config_file: ".swiftlint.yml ",     # The path of the configuration file (optional)
      ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )
  end

  

end
